@startuml csp_setting

package "HTTP header" as http_header {
  package "예시" as csp_http_header_example {
    component csp_http_header_img [
      * HTTP 헤더에 CSP가 설정된 예시(Mozilla Web Docs)
      "<img:csp_http_header.png{scale=0.3}>" 
    ]
  }
  package "구현방법" as csp_http_header_impl {
    component csp_http_header_example_impl [
      * 구현방법을 여기에 작성
      ** 한 개는 express
      ** 한 개는 SSR로 http 헤더 설정하는 방법
    ]
  }

  csp_http_header_example -right[#white]- csp_http_header_impl
}

package "<meta http-equiv='Content-Security-Policy' />" as meta {
  package "예시" as csp_meta_example {
    component csp_meta_img [
      * meta tag 설정된 예시
      ** http head 태그 내에 meta tag 이용해서 추가된 정도만 보여줌
    ]
  }
  package "구현방법" as csp_meta_impl {
    component csp_meta_example_impl [
      * react 기준으로 구현방법을 여기에 작성. 여러 가지 방법이 있음을 알림
      ** public/index.html
      ** webpack으로 bundling 할 때, CspWebpackPlugin
      ** react-helmet
      ** nonce(추후 설명 예정)
    ]
  }

  csp_meta_example -right[#white]- csp_meta_impl
}

http_header -down[#white]- meta

note left of http_header
* HTTP 헤더에 Content-Security-Policy를 설정함.
* 서버에서 설정
end note

note left of meta
* <html> 태그 내부에 <meta> 태그를 이용하여
  Content-Security-Policy를 설정함.
* 서버 / 클라이언트 모두에서 설정 가능
end note

@enduml